# Taskfile for repacku (placed inside package directory)
# 参考 rawfilter 的使用风格，后续可在重写为 Typer CLI 后继续复用。
# 使用: 在此目录运行 `lata` 或 `task <目标>`

version: '3'

vars:
  PYTHON_CMD: repacku

# 若未来迁移到 Typer 并加入 --yes / --analyze-only 等参数，可在此扩展。

tasks:
  default:
    desc: 显示所有任务
    cmds:
      - task --list
    silent: true

  image-only:
    desc: "仅针对图片类型(默认示例) 从剪贴板读取路径"
    cmds:
      - "{{.PYTHON_CMD}} compress --clipboard --types image --delete-after"

  gallery-pack:
    desc: "画集模式 (.画集 目录批量处理)"
    cmds:
      - "{{.PYTHON_CMD}} compress --clipboard --gallery --delete-after"


  gallery-and-single:
    desc: "先画集再单层 (可并用)"
    cmds:
      - "{{.PYTHON_CMD}} compress --clipboard --gallery --single --delete-after"

  single-pack:
    desc: "单层打包 (子目录+散图)"
    cmds:
      - "{{.PYTHON_CMD}} compress --clipboard --single --delete-after"


