# Taskfile for repacku (placed inside package directory)
# 参考 rawfilter 的使用风格，后续可在重写为 Typer CLI 后继续复用。
# 使用: 在此目录运行 `lata` 或 `task <目标>`

version: '3'

vars:
  PYTHON_CMD: repacku

# 若未来迁移到 Typer 并加入 --yes / --analyze-only 等参数，可在此扩展。

tasks:
  default:
    desc: 显示所有任务
    cmds:
      - task --list
    silent: true

  basic:
    desc: "从剪贴板读取路径进行分析+可选压缩 (按提示确认)"
    cmds:
      - "{{.PYTHON_CMD}} --clipboard"

  image-only:
    desc: "仅针对图片/文档类型(默认示例) 从剪贴板读取路径"
    cmds:
      - "{{.PYTHON_CMD}} --clipboard --types image"

  single-pack:
    desc: "单层打包模式 (对子目录逐个压缩)"
    cmds:
      - "{{.PYTHON_CMD}} --clipboard --single"

  gallery-pack:
    desc: "画集模式 (.画集 目录批量处理)"
    cmds:
      - "{{.PYTHON_CMD}} --clipboard --gallery"

  delete-after:
    desc: "压缩后删除源文件 (危险操作! 请确认路径)"
    cmds:
      - "{{.PYTHON_CMD}} --clipboard --delete-after"

  image-delete:
    desc: "仅图片类型并压缩后删除"
    cmds:
      - "{{.PYTHON_CMD}} --clipboard --types image --delete-after"

  full-image:
    desc: "图片类型 + 单层打包 + 画集模式组合示例 (可能重复, 按需调整)"
    cmds:
      - "{{.PYTHON_CMD}} --clipboard --types image --single --gallery"

  cli:
    desc: "自定义参数透传 (例: task cli -- --path D:/Data --types image)"
    cmds:
      - "{{.PYTHON_CMD}} {{.CLI_ARGS}}"

  # 预留: 将来 Typer 版本添加 --yes/--analyze-only / --no-compress 后可改写以下任务
  # analyze-only:
  #   desc: 仅生成 *_config.json (待 CLI 支持 --analyze-only 后启用)
  #   cmds:
  #     - "{{.PYTHON_CMD}} --clipboard --types image --analyze-only"

